global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"

    static_configs:
      - targets: ["localhost:9090"]
      
  - job_name: "node"
  
    scrape_interval: 10s
    static_configs:
      - targets: ['172.29.0.1:9100']
      
  - job_name: 'grafana_metrics'

    scrape_interval: 15s
    scrape_timeout: 5s
    
    static_configs:
      - targets: ['grafana:3000']
      
  - job_name: cadvisor
   
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor:8080']
      