server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log
  - targets:
      - localhost
    labels:
      job: cronlogs
      __path__: /var/log/cron*
  - targets:
      - localhost
    labels:
      job: mailloglogs
      __path__: /var/log/maillog*
  - targets:
      - localhost
    labels:
      job: messageslogs
      __path__: /var/log/messages*
  - targets:
      - localhost
    labels:
      job: securelogs
      __path__: /var/log/secure*